function Hd = LP44100_Fs125e3
%LP44100_FS125E3 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 12-Mar-2022 09:49:52

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 125;  % Sampling Frequency

N     = 200;   % Order
Fpass = 44.1;  % Passband Frequency
Fstop = 47;    % Stopband Frequency
Wpass = 1;     % Passband Weight
Wstop = 80;    % Stopband Weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
